<a href="https://colab.research.google.com/github/Mustakim-Mh/1st/blob/main/Class11_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[10,12,13]])
print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [10 12 13]]


In [ ]:
zeros = np.zeros([2,3,2])
print(zeros)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
zeros = np.zeros([3])
print(zeros)

[0. 0. 0.]


In [ ]:
ones = np.ones([2,3,2])
print(ones)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
arange = np.arange(0,10,2)
print(arange)

[0 2 4 6 8]


In [ ]:
arange = np.arange(0,10,.25)
print(arange)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75
 7.   7.25 7.5  7.75 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [ ]:
linspace = np.linspace(0,1,6)
print(linspace)

[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[1:4])

10
30
50
[20 30 40]


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[10,12,13]])
print(arr_2d[0,0])
print(arr_2d[2,1])


1
12


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[0,1])
print(arr_2d[:,0])
print(arr_2d[1:,0])
print(arr_2d[:,0:1])
print(arr_2d[1:,0:1])

2
[1 4 7]
[4 7]
[[1]
 [4]
 [7]]
[[4]
 [7]]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1+arr2)
print(arr1*arr2)
print(arr2/arr1)

[5 7 9]
[ 4 10 18]
[4.  2.5 2. ]


In [ ]:
arr = np.array([1,2,3])
print(arr+10)

[11 12 13]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(np.dot(arr1,arr2))

[[19 22]
 [43 50]]


In [ ]:
arr=np.array([10,20,30,40,50])
print(np.mean(arr))
print(np.std(arr))
print(np.sum(arr))

30.0
14.142135623730951
150


In [ ]:
arr = np.arange(1,13)
arr_reshaped = arr.reshape(3,4)
arr_reshaped_2 = arr.reshape(4,3)
print(arr)
print(arr_reshaped)
print(arr_reshaped_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.arange(1,61)
arr_reshaped = arr.reshape(3,4,5)

print(arr)
print(arr_reshaped)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])

print(np.concatenate((arr1,arr2),axis=0))

[[1 2]
 [3 4]
 [5 6]]
